# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 694985e0712eedd98b980251c263552aa97ef214645fca25a4dbf147ab6e2eeb638983f0114c3a025b32b039d1dcce0dfa89c7d8511f9a1c236021c84c870b68

test:
  secret_key_base: d998926da0985173d9707b9fa14546550ca31d592ff7782347fcf46ec6474c1f506c228e0cd9f14a68ef9f6b4b5ae6f64614e048936c74ac2f2298b68cd3e61d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
